apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
spec:
  channel: stable
  installPlanApproval: Automatic
  name: nfd
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: nfd.4.10.0-202306170106
