apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/instance: zookeeper
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: zookeeper
    role: zookeeper
automountServiceAccountToken: false
