apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: curator
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: curator
  name: curator-leader-election-rolebinding
  namespace: curator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: curator-leader-election-role
subjects:
- kind: ServiceAccount
  name: curator-controller-manager
  namespace: curator-system
