apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: curator
resources:
  - ../../base/core/namespaces/curator-system
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/curator
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/curator
  - ../../base/rbac.authorization.k8s.io/clusterroles/curator
