apiVersion: keycloak.nerc.mghpcc.org/v1
kind: KeycloakAuthorization
metadata:
  name: nerc
  labels:
    app: keycloak
    realm: NERC
spec:
  cleanupUndefinedAuthorizations: true
  keycloak:
    baseUrl: https://keycloak.apps.obs.nerc.mghpcc.org
    adminSecret:
      name: keycloak-initial-admin
      usernameKey: username
      passwordKey: password
  realm:
    id: NERC
    clients:
      - id: ai4cloudops
        authorizationSettings:
          resources:
            - name: cluster
              displayName: cluster
              scopes:

                - id: cluster-all
                  name: all clusters
                  displayName: all clusters
                - id: cluster-nerc-ocp-infra
                  name: nerc-ocp-infra
                  displayName: nerc-ocp-infra cluster
                - id: cluster-nerc-ocp-obs
                  name: nerc-ocp-obs
                  displayName: nerc-ocp-obs cluster
                - id: cluster-nerc-ocp-prod
                  name: nerc-ocp-prod
                  displayName: nerc-ocp-prod cluster
                - id: cluster-nerc-ocp-test
                  name: nerc-ocp-test
                  displayName: nerc-ocp-test cluster

            - name: namespace
              displayName: namespace
              scopes:
                - id: namespace-all
                  name: all namespaces
                  displayName: all namespaces
                - id: namespace-rhods-notebooks
                  name: rhods-notebooks
                  displayName: rhods-notebooks namespace

          policies:
            - id: client-ai4cloudops
              name: client-ai4cloudops
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                client:
                  clients:
                    - ai4cloudops
            - id: group-nerc-ai4cloudops
              name: group-nerc-ai4cloudops
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                group:
                  groups:
                    - id: nerc-ai4cloudops
            - id: group-nerc-ops
              name: group-nerc-ops
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                group:
                  groups:
                    - id: nerc-ops

          permissions:
            - name: group-nerc-ops-cluster-all
              client: ai4cloudops
              policy: group-nerc-ops
              resource: cluster
            - name: group-nerc-ops-namespace-all
              client: ai4cloudops
              policy: group-nerc-ops
              resource: namespace
            - name: group-nerc-ai4cloudops-namespace-all
              client: ai4cloudops
              policy: group-nerc-ai4cloudops
              resource: namespace
            - name: client-ai4cloudops-namespace-all
              client: ai4cloudops
              policy: client-ai4cloudops
              resource: namespace
            - name: group-nerc-ai4cloudops-cluster-nerc-ocp-prod
              client: ai4cloudops
              policy: group-nerc-ai4cloudops
              resource: cluster
              scope: nerc-ocp-prod
            - name: client-ai4cloudops-cluster-nerc-ocp-prod
              client: ai4cloudops
              policy: client-ai4cloudops
              resource: cluster
              scope: nerc-ocp-prod
