apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: curator
resources:
  - fetchdata.curator.curator.yaml
  - reportapis.curator.curator.yaml
  - reports.curator.curator.yaml
