apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-admin-credentials
  namespace: minio
spec:
<<<<<<< HEAD
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
=======
>>>>>>> 09d2be4 (feat: add minio to nerc-ocp-obs cluster)
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-obs/minio/minio-admin-credentials
