kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-allowlist
  namespace: open-cluster-management-observability
data:
  metrics_list.yaml: |
    names:
      - kube_persistentvolumeclaim_resource_requests_storage_bytes
      - kube_pod_spec_volumes_persistentvolumeclaims_info
      - kube_persistentvolumeclaim_info
      - kube_storageclass_info
      - kubelet_volume_stats_used_bytes
      - node_network_receive_bytes_total
      - node_network_transmit_bytes_total
      - node_network_transmit_errs_total
      - node_network_transmit_packets_total
