apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: openshift-custom-metrics-autoscaler-operator
resources:
- ../../base/core/namespaces/openshift-keda
- ../../base/operators.coreos.com/operatorgroups/openshift-keda
- ../../base/operators.coreos.com/subscriptions/openshift-custom-metrics-autoscaler-operator
