apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - objectbucketclaims
  - externalsecrets
  - configmaps
  - lokistacks
  - clusterroles
  - clusterrolebindings
  - serviceaccounts
  - securitycontextconstraints
  - daemonsets
commonLabels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/component: lokistack
  app.kubernetes.io/part-of: cluster-logging
