apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-config
  namespace: curator-system
spec:
  dataFrom:
  - extract:
      key: nerc/nerc-ocp-test/curator/postgres
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: nerc-secret-store
