apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: block-public-ssh-worker
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: block-public-ssh.service
          enabled: true
          contents: |
            [Unit]
            Description=Block ssh from anywhere but private network
            Requires=sshd.service
            Before=sshd.service

            [Service]
            Type=oneshot
            ExecStart=/usr/sbin/iptables -I INPUT -p tcp --dport 22 ! -s 192.168.50.0/24 -j DROP

            [Install]
            WantedBy=multi-user.target
