apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production-dns01
spec:
  acme:
    email: help@nerc.mghpcc.org
    privateKeySecretRef:
      name: letsencrypt-production-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cnameStrategy: Follow
        route53:
          region: us-east-1
          accessKeyIDSecretRef:
            key: AWS_ACCESS_KEY_ID
            name: aws-route53-credentials
          secretAccessKeySecretRef:
            key: AWS_SECRET_ACCESS_KEY
            name: aws-route53-credentials
      selector:
        dnsZones:
        - shift.nerc.mghpcc.org
