apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: node-feature-discovery
resources:
- ../../base/core/namespaces/node-feature-discovery
- ../../base/operators.coreos.com/operatorgroups/node-feature-discovery
- ../../base/operators.coreos.com/subscriptions/node-feature-discovery
