apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: curator-manager-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - curator.curator
  resources:
  - fetchdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - curator.curator
  resources:
  - fetchdata/finalizers
  verbs:
  - update
- apiGroups:
  - curator.curator
  resources:
  - fetchdata/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - curator.curator
  resources:
  - reportapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - curator.curator
  resources:
  - reportapis/finalizers
  verbs:
  - update
- apiGroups:
  - curator.curator
  resources:
  - reportapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - curator.curator
  resources:
  - reports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - curator.curator
  resources:
  - reports/finalizers
  verbs:
  - update
- apiGroups:
  - curator.curator
  resources:
  - reports/status
  verbs:
  - get
  - patch
  - update
