apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: github
      mappingMethod: claim
      type: GitHub
      github:
        clientID: e87d9a48533084f2aa5f
        clientSecret:
          name: github-client-secret
        teams:
          - ocp-on-nerc/nerc-ops
          - ocp-on-nerc/nerc-logs-metrics
          - ocp-on-nerc/nerc-rhods
