apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: crunchy-postgres-operator
resources:
- ../../base/operators.coreos.com/subscriptions/crunchy-postgres-operator
