apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- project-robbie-allow-sys-admin.yaml

transformers:
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: notImportantHere
    namespace: project-robbie-6f75ac
  setRoleBindingSubjects: allServiceAccounts
  fieldSpecs:
  - path: metadata/namespace
    create: true
