kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: loki-promtail
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowHostDirVolumePlugin: true
allowPrivilegeEscalation: true
allowHostPID: true
allowPrivilegedContainer: true
users:
  - system:serviceaccount:openshift-logging:loki-promtail
