apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-promtail
  namespace: openshift-logging
  labels:
    app.kubernetes.io/name: promtail
data:
  promtail.yaml: |
    clients:
      - url: https://lokistack-openshift-operators-redhat.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/logs/v1/infrastructure/loki/api/v1/push
        bearer_token_file: /var/run/lokistack-gateway-bearer-token/token
        backoff_config:
          min_period: 100ms
          max_period: 5s
          max_retries: 5
        batchsize: 102400
        batchwait: 1s
        external_labels: {}
        timeout: 10s
        tls_config:
          cert_file: /var/run/lokistack-gateway-bearer-token/tls.crt
          key_file: /var/run/lokistack-gateway-bearer-token/tls.key
          ca_file: /var/run/lokistack-gateway-bearer-token/ca-bundle.crt
        tenant_id: systemd-journal
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
      log_level: debug
    target_config:
      sync_period: 10s
    scrape_configs:
      - job_name: journal
        journal:
          max_age: 12h
          path: /var/log/journal
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels:
            - __journal__systemd_unit
            target_label: unit
          - source_labels:
            - __journal__hostname
            target_label: hostname
