apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: log-backup
  namespace: openshift-logging
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: log-backup
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-infra/openshift-storage/nerc-shift-1-backups
