apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solr
resources:
- networkpolicy.yaml
- configmap.yaml
- service-headless.yaml
- service.yaml
- serviceaccount.yaml
- statefulset.yaml
