apiVersion: v1
kind: ServiceAccount
metadata:
  name: solr
  labels:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: solr
    app.kubernetes.io/component: solr
automountServiceAccountToken: false
