apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    name: nerc-secret-store
    kind: SecretStore
  target:
    name: github-client-secret
    # Prevent generated Secret from inheriting the labels from this
    # ExternalSecret. OpenShift will create a copy of the Secret, and the
    # labels will cause it to show up as out-of-sync in ArgoCD. See
    # https://github.com/OCP-on-NERC/operations/issues/42 for additional
    # details.
    template:
      metadata:
        labels: {}
  data:
  - secretKey: clientSecret
    remoteRef:
      key: nerc/nerc-ocp-test/openshift-config/github-client-secret
      property: clientSecret
