apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: nerc-secret-store
spec:
  provider:
    vault:
      server: "https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/"
      path: "nerc"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes/nerc-ocp-prod
          role: secret-reader
          secretRef:
            name: "vault-secret-reader"
            key: "token"
