apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack
  namespace: openshift-operators-redhat
spec:
  limits:
    global:
      ingestion:
        ingestionBurstSize: 10
        ingestionRate: 10
  managementState: Managed
  storage:
    secret:
      name: thanos-object-storage
      type: s3
    tls:
      caName: lokistack-ca-bundle-custom
  tenants:
    mode: openshift-logging
  size: 1x.medium
  storageClassName: ocs-external-storagecluster-ceph-rbd
