apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: solr-secret
  namespace: solr
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: solr-secret
  dataFrom:
    - extract:
        key: $ENV/$CLUSTER/solr-password
