apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-admin-credentials
  namespace: minio
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: nerc/hypershift1/minio/minio-admin-credentials
